version: 2.1
description: My User-Defined ORB 

orbs:
  my-orb:
    orbs:
      codecov: circleci/codecov-clojure@0.0.4
    executors:
      specialthingsexecutor:
        docker:
          - image: circleci/php
    commands: 
      dospecialthings:
        steps:
          - run: echo "Hello"
          - run: echo "World" 
          
    jobs:
      myjob:
        executor: specialthingsexecutor
        steps:
         - dospecialthings 
workflows:
  main: 
    jobs:
      - my-orb/myjob 
