version: 2.1
description: My User-Defined ORB 

orbs:
  my-orb:
    orbs:
      codecov: circleci/codecov-clojure@0.0.4
    executors:
      specialthingsexecutor:
        docker:
          - image: circleci/ruby:1.4.2.
    commands: 
      dospecialthings:
        steps:
          - run: echo "Some Special Things"
    jobs:
      myjob:
        executor: specialthingsexecutor
        steps:
          - dospecialthings 
workflows:
  main: 
    jobs:
      - my-orb/myjob
