version: 2.1
description: My User-Defined ORB 

orbs:
  my-orb:
    orbs:
      codecov: circleci/codecov-clojure@0.0.4
    executors:
      specialthingsexecutor:
        docker:
          - image: circleci/php
    commands: 
      dospecialthings:
        steps:
          - run: echo "Some Special Things"
    jobs:
       executor: specialthingsexecutor
       steps:
         - dospecialthings 
workflows:
  main: 
    jobs:
      - my-orb/myjob
